### ISSUE TITLE
Unable to process `daily_max()` if data contain missing values

### ISSUE THREAD

**Issue by dkmckellar** [kjell-ohlsson/python-intermediate-inflammation#17]
https://github.com/kjell-ohlsson/python-intermediate-inflammation/blob/20abba232325641020d787d50fd01ff7ae13539c/inflammation/models.py#L38

@kjell-ohlsson This function seems to break if my data contain `np.nan`'s - is there a suitable workaround?

**Comment by Nev-Cope** [comment]
@kjell-ohlsson could change to the function np.nanmax?

**Comment by Nev-Cope** [comment]
Updated daily_max function, and added some tests
